version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    networks:
      - application-network
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_PORT=6379
    volumes:
      - redis_data:/bitnami/redis/data

  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: mongo
    networks:
      - application-network
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_DATABASE=mongo_database
      - MONGODB_USERNAME=mongo_user
      - MONGODB_PASSWORD=mongo_password
    volumes:
      - mongodb_data:/bitnami/mongodb

  app:
    container_name: app
    build: ./application
    networks:
      - application-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis_password
      - REDIS_PORT=6379
      - MONGODB_DATABASE=mongo_database
      - MONGODB_USERNAME=mongo_user
      - MONGODB_PASSWORD=mongo_password
    depends_on:
      - redis
      - mongo


volumes:
  redis_data:
  mongodb_data:

networks:
    application-network:
