version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    networks:
      - application-network
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=redis_password
      - REDIS_USERNAME=redis_user
    volumes:
      - redis_data:/bitnami/redis/data

  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: mongo
    networks:
      - application-network
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mongo_database
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    volumes:
      - mongodb_data:/bitnami/mongodb

  app:
    container_name: app
    build: ./app
    networks:
      - application-network
    depends_on:
      - redis
      - mongo


volumes:
  redis_data:
  mongodb_data:

networks:
    application-network:
